### ISSUE TITLE
Suggestion: add Nostr URLs section and https redirects

### ISSUE THREAD

**Issue by theDavidCoen** [nostr-resources/nostr-resources.github.io#17]
You could add a Nostr URLs section in which you give a brief explanation of what `nostr:` handle is (NIP-05) and how to do https redirects.

I have a guide/tool here you can use if you want https://nostredirect.davidcoen.it.

Here the result:
https://snort.social/e/note1as34wa4h7q36can2lvsh5q898z0xgsc24up8yst8u9c9zw47avkswz530f and https://snort.social/e/note1wmzkd08jjlw62trxtctxelrueu82e5cvkfk04tyyga9kz8fp7c6qxhgruv

**Comment by dergigi** [comment]
Will do! Thanks for the suggestion! 💜
