### ISSUE TITLE
Add Alby wallet to "Receiving Zaps" section

### ISSUE THREAD

**Issue by MoritzKa** [nostr-resources/nostr-resources.github.io#27]
Thanks for putting this website together. I find it a great resource, especially for beginners. 

Is there a chance to update the ["Receiving Zaps" section](https://nostr-resources.com/#receiving-zaps) with Alby?

"To receive zaps you need a lightning wallet that supports [NIP-57](https://github.com/nostr-protocol/nips/blob/master/57.md). Three popular custodial solutions are [Stacker News](https://stacker.news/), [Lightning Tip Bot](https://ln.tips/) and [Alby](https://getalby.com/).

**Comment by dergigi** [comment]
Done! Thanks for tracking an issue 🙏💜

**Comment by MoritzKa** [comment]
Thanks a lot.
